### ISSUE TITLE
Make it easier to test specific git hashes of Stan and Math repo as well

### ISSUE THREAD

**Issue by seantalts** [stan-dev/performance-tests-cmdstan#1]
Right now, `compare-git-hashes.sh` works only on cmdstan git hashes. Due to the intricate submodule substructure of our codebase, this requires doing a bunch of extra steps in both Stan and CmdStan repos every time you want to test a Math repo commit. I think we could either modify this script or provide another script to test Stan and Math git hashes as well.

**Comment by WardBrian** [comment]
Closed by #11
