### ISSUE TITLE
make runPerformanceTests run on Windows

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/performance-tests-cmdstan#20]
Not a huge priority but it would simplify testing with Windows. I can add this if you give me writing permissions to the repo. 
 
In order to make it work on windows we need: 
- dynamic folder separators (using `os.path.join()` should do it)
- add exe to make path if running windows
- shexec("cd cmdstan") doesnt work. to make it work I modified shexec so that its

```
def shexec(command, wd = "."):
    print(command)
    returncode = subprocess.call(command, shell=True, cwd=wd)
    if returncode != 0:
        raise FailedCommand(returncode, command)
    return returncode
```
and then change make to 
```
def make(targets, j=8):
    shexec("make -j{} {}"
           .format(j, " ".join("..\\" + t for t in targets)), wd = "cmdstan")
```

**Comment by seantalts** [comment]
Submit a PR?

**Comment by rok-cesnovar** [comment]
Sure, I just wanted to avoid making a fork :)
