### ISSUE TITLE
Add compilation regression test models to this repository

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/performance-tests-cmdstan#30]
There are Stan models that could be used for compilation regression testing (checking that everything compiles) only. For now just tracking down models that could be used for that. There are some models from "power users" and packages that are quite complicated, big and use a ton of features. We want to make sure those compile always. Adding posterior validation for these would probably be a bit more involved.

- OncoBayes2 models from @wds15 et al
- [ctsem models](https://github.com/cdriveraus/ctsem/tree/master/src/stan_files) from @cdriveraus et al
- [rater models](https://github.com/jeffreypullin/rater/tree/master/inst/stan) from @jeffreypullin et al

Other ideas:
- https://github.com/epiforecasts/EpiNow2/tree/master/inst/stan
- https://github.com/ecmerkle/blavaan/tree/master/src/stan_files
- brms generated models

Also taking suggestions.

We already have models from rstanarm and prophet in the testing pipeline.

**Comment by rok-cesnovar** [comment]
@WardBrian I just realized that we probably can't add these models to the stanc3 repo as all of them are GPL-2 or GPL-3 licensed. 

Unless the authors somehow approve them being added to our repo under a different license. We would not actually distribute them, just use them in tests, but this licensing stuff is a slippery slope to me :)

We could add them to this repo as we probably care much less under which license this repo uses?

**Comment by cdriveraus** [comment]
I also have little clue re licenses, but would be happy to have the ctsem model included. I can post this separately in case it helps...
