### ISSUE TITLE
Failing Numerical Accuracy & Shotgun Performance

### ISSUE THREAD

**Issue by serban-nicusor-toptal** [stan-dev/performance-tests-cmdstan#50]
master pipeline is failing in the `Numerical Accuracy and Performance Tests on Known-Good Models` step and looks like `Shotgun Performance Regression Tests` is failing also.
See: https://github.com/stan-dev/performance-tests-cmdstan/issues/49 fir Numerical accuracy `irt_2pl.stan` and 
[Failed pipeline](https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FBleedingEdgeCompilersMonthly/detail/BleedingEdgeCompilersMonthly/72/pipeline) for `Shotgun Performance` failing in another pipeline ( same logic as here ).

I've also found out that `-march=core2` is not compatible with Mac M1 architecture. https://stackoverflow.com/questions/72303819/c-clion-error-the-clang-compiler-does-not-support-march-core2

**Comment by SteveBronder** [comment]
Is it just the mac tests that are failing?

**Comment by SteveBronder** [comment]
If so then I think we can just remove that? idt it should be on at all for m1 macs

**Comment by serban-nicusor-toptal** [comment]
Both the linux and the mac ones.
linux: https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FBleedingEdgeCompilersMonthly/detail/BleedingEdgeCompilersMonthly/72/pipeline/

**Comment by serban-nicusor-toptal** [comment]
For the `-march=core2` I've already figured it out in another PR, will push it to master here a bit later. We will use just the Intel mac for these tests.
