### ISSUE TITLE
Posting of performance comment broken

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/performance-tests-cmdstan#59]
Creating this mainly so @serban-nicusor-toptal and I don't forget to look into this once we have the other pipelines green again

**Comment by serban-nicusor-toptal** [comment]
Started [working on it](https://github.com/stan-dev/performance-tests-cmdstan/pull/64), trying to replace the getRawBuild call with reading the log file on the local agent. I'm currently stuck on permissions for approving the scripts usage in https://jenkins.flatironinstitute.org/job/Stan/job/CmdStan%20Performance%20Tests/job/ci-fix-posting-results/4/console

**Comment by dylex** [comment]
Is there anyway to do this without using unsafe APIs? Since you end up running a shell script anyway, can you get the log that way, or through http to jenkins?

**Comment by dylex** [comment]
Reading the log file directly will only work on the main jenkins node anyway, which not all builds run on.

**Comment by serban-nicusor-toptal** [comment]
I'll give the [consoleFull ](https://jenkins.flatironinstitute.org/job/Stan/job/CmdStan%20Performance%20Tests/job/ci-fix-posting-results/4/consoleFull)endpoint a try.

**Comment by serban-nicusor-toptal** [comment]
I've managed to get rid of all the unsafe calls, see https://github.com/stan-dev/performance-tests-cmdstan/pull/64/files
Seems to be working fine now, tested it in a dummy PR of mine in Stan. Closing this.
